# -*- coding: utf-8 -*-
"""blip_digital_twin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7qntasCJf3jc2cJJygTqEmtMDNBsUuZ
"""

# !pip install -q transformers accelerate bitsandbytes pdfplumber torch sentencepiece flask flask-cors pyngrok
# !pip install torch flask-ngrok faiss-cpu regex
# !pip install flask flask-cors pyngrok
# !pip install boto3
# !pip install flask-sock simple-websocket websockets

import os, re, io, json, zipfile, tempfile, datetime, uuid, threading
import torch
import re
import threading
import datetime
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from pyngrok import ngrok
import traceback
from flask import Response, stream_with_context
import boto3
from flask_sock import Sock
import uuid
import tempfile

# ---------------- CONFIG ---------------- #
os.environ["NGROK_AUTH_TOKEN"] = "3365NptIuQXwEr8DryJhrQbVNe8_7eBQ6XLZFzcoyzRybeude"

app = Flask(__name__)
sock = Sock(app)
CORS(app)
ALLOWED_EXTENSIONS = {'json'}

import pandas as pd
import math
from collections import deque
from datetime import datetime

# app = Flask(__name__)

BATTERY_COEFFICIENTS = {
    "LFP": {
        "cycle_coeff": 0.000015,
        "calendar_coeff": 0.00000005,
        "activation_energy": 32000
    },
    "NMC": {
        "cycle_coeff": 0.000025,
        "calendar_coeff": 0.00000008,
        "activation_energy": 28000
    },
    "NCA": {
        "cycle_coeff": 0.00003,
        "calendar_coeff": 0.0000001,
        "activation_energy": 26000
    },
    "Others": {
        "cycle_coeff": 0.00002,
        "calendar_coeff": 0.00000007,
        "activation_energy": 30000
    }
}

R = 8.314

class BatteryDegradationEngine:
    def __init__(
            self,
            battery_type="Others",
            initial_soh=100):

        self.battery_type = battery_type
        self.initial_soh = initial_soh
        self.coeff = BATTERY_COEFFICIENTS.get(
            battery_type,
            BATTERY_COEFFICIENTS["Others"]
        )
        self.cycle_degradation = 0
        self.calendar_degradation = 0
        self.energy_throughput = 0
        self.last_timestamp = None
        self.temperature_history = deque(maxlen=1000)
        self.soc_history = deque(maxlen=1000)

    def charging_state(self,current):

        if current > 0:
            return "Charging"

        elif current < 0:
            return "Discharging"

        return "Idle"

    # def cycling_aging(self,data):
    #     cycle_count = float(data.get("CycleCount",0))
    #     soc = float(data.get("SOC",50))
    #     current = abs(float(data.get("Current",0)))
    #     power = abs(float(data.get("Power(W)",0)))
    #     remain_cap=float(data.get("RemainCap",1))
    #     full_cap=float(data.get("FullCap",1))
    #     max_vol=float(data.get("MaxVol",0))
    #     min_vol=float(data.get("MinVol",0))
    #     avg_temp=float(data.get("MTemp",25))
    #     dod=(100-soc)/100
    #     c_rate=current/max(full_cap,1)
    #     capacity_fade=max(
    #         0,
    #         (full_cap-remain_cap)/max(full_cap,1)
    #     )
    #     voltage_stress=max_vol-min_vol

    #     temperature_factor=math.exp(
    #         (avg_temp-25)/30
    #     )
    #     self.energy_throughput += power/3600
    #     cycle_deg=(
    #         self.coeff["cycle_coeff"]
    #         *cycle_count
    #         *(1+dod)
    #         *(1+c_rate)
    #         *(1+capacity_fade)
    #         *(1+voltage_stress)
    #         *temperature_factor
    #         *(1+self.energy_throughput/100000)
    #     )
    #     # self.cycle_degradation=cycle_deg
    #     self.cycle_degradation += cycle_deg

    def cycling_aging(self,data):
        cycle_count=float(data.get("CycleCount",0))
        soc=float(data.get("SOC",50))
        current=abs(float(data.get("Current",0)))
        power=abs(float(data.get("Power(W)",0)))
        remain_cap=float(data.get("RemainCap",1))
        full_cap=float(data.get("FullCap",1))
        max_vol=float(data.get("MaxVol",0))
        min_vol=float(data.get("MinVol",0))
        avg_temp=float(data.get("MTemp",25))
        dod=(100-soc)/100
        c_rate=current/max(full_cap,1)
        capacity_fade=max(
            0,
            (full_cap-remain_cap)/max(full_cap,1)
        )

        voltage_stress=max_vol-min_vol
        temperature_factor=math.exp(
            (avg_temp-25)/30
        )

        self.energy_throughput += (power / 3600)
        throughput_factor = ( 1 + self.energy_throughput /(full_cap * max(max_vol,1) *1000) )

        incremental_deg=(
            self.coeff["cycle_coeff"] *(1+dod) *(1+c_rate) *(1+capacity_fade) *(1+voltage_stress) *temperature_factor * throughput_factor *(power/1000) /3600
        )

        self.cycle_degradation += incremental_deg


    def calendar_aging(self,data):
        current_time=data.get("Time")
        if current_time:
            try:
                ts=datetime.strptime(current_time, "%m/%d/%Y %I:%M:%S %p")
            except:
                ts=datetime.now()
        else:
            ts=datetime.now()

        if self.last_timestamp is None:
            self.last_timestamp=ts
            return
        elapsed=(ts-self.last_timestamp).total_seconds()
        self.last_timestamp=ts
        temp=float(data.get("MTemp",25))
        soc=float(data.get("SOC",50))
        temp_kelvin=temp+273.15
        arrhenius=math.exp((-self.coeff["activation_energy"])/(R*temp_kelvin))
        soc_factor=1+(soc/100)

        calendar_deg=(
            self.coeff["calendar_coeff"]
            *elapsed
            *arrhenius
            *soc_factor
        )

        self.calendar_degradation += calendar_deg

    def process(self,data):
        self.cycling_aging(data)
        self.calendar_aging(data)
        total_soh=(self.initial_soh-self.cycle_degradation-self.calendar_degradation)

        total_soh=max(0,min(100,total_soh))
        current=float(data.get("Current",0))
        output={
            "timestamp":
                str(
                    data.get("Time","")
                ),

            "soh":
                round(
                    total_soh,
                    4
                ),

            "battery_capacity_ah":
                float(
                    data.get("FullCap",0)
                ),

            "current_a":
                current,

            "power_w":
                float(
                    data.get("Power(W)",0)
                ),

            "voltage_v":
                float(
                    data.get(
                        "Voltage(V)",
                        data.get("TotalVol",0)
                    )
                ),
            "temperature_c":
                float(
                    data.get("MTemp",0)
                ),
            "charging_state":
                self.charging_state(
                    current
                )

        }
        return output


def validate_json(data):
    required_fields=["battery_type","total_cells"]
    missing=[]
    for field in required_fields:
        if field not in data:
            missing.append(field)

    if missing:
        raise Exception(f"Missing fields: {missing}")

    n=data["total_cells"]

    for i in range(1,n+1):
        if f"Cell_{i}" not in data:
            raise Exception(f"Missing Cell_{i}")

        if f"Temp{i}" not in data:
            raise Exception(f"Missing Temp{i}")


@app.route("/battery-soh",methods=["POST"])
def calculate_soh():
    try:
        if "battery_data" not in request.files:
            return jsonify({
                "error":
                "'battery_data' JSON file required"

            }),400

        file=request.files["battery_data"]
        if not file.filename.lower().endswith(".json"):
            return jsonify({
                "error":
                "Only JSON allowed"
            }),400
        records=json.load(file)
        if not isinstance(records,list):
            records=[records]

        results=[]
        first=records[0]
        validate_json(first)
        engine=BatteryDegradationEngine(
            battery_type=first.get("battery_type","Others"),
            initial_soh=float(first.get("initial_soh",100))
        )

        for row in records:
            validate_json(row)
            output=engine.process(row)
            results.append(output)
        result_bytes=json.dumps(results,indent=2).encode("utf-8")

        return send_file(
            io.BytesIO(
                result_bytes
            ),
            as_attachment=True,
            download_name=
            "battery_soh_results.json",
            mimetype=
            "application/json"
        )
    except Exception as e:
        return jsonify({"error":str(e)}),500

@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status":"healthy"})

# if __name__=="__main__":
#     app.run(
#         host="0.0.0.0",
#         port=5000,
#         debug=True
#     )

client_engines = {}

@sock.route("/battery-stream")
def battery_stream(ws):
    client_id = id(ws)
    try:
        engine = None
        while True:
            # Receive next message from websocket
            message = ws.receive()
            if message is None:
                break
            try:
                data = json.loads(message)
            except Exception as e:
                ws.send(json.dumps({
                    "error": f"Invalid JSON: {str(e)}"
                }))
                continue

            # Optional close message from client
            if data.get("action") == "close":
                ws.send(json.dumps({"status": "Connection closed"}))
                break
            try:
                validate_json(data)
                # Create engine only once. Maintain state across messages

                if engine is None:
                    battery_type = data.get(
                        "battery_type",
                        "Others"
                    )
                    initial_soh = float(
                        data.get(
                            "initial_soh",
                            100
                        )
                    )
                    engine = BatteryDegradationEngine(
                        battery_type=battery_type,
                        initial_soh=initial_soh
                    )
                    client_engines[client_id] = engine
                output = engine.process(data)
                ws.send(json.dumps(output))

            except Exception as e:
                ws.send(json.dumps({"error": str(e)}))

    finally:
        # Cleanup after disconnect
        if client_id in client_engines:
            del client_engines[client_id]
        try:
            ws.close()
        except:
            pass

def run_flask(port=5008):
    app.run(host="0.0.0.0", port=port, debug=False)

def main():
    use_ngrok = os.getenv("USE_NGROK", "false").lower() == "true"
    port = int(os.getenv("PORT", 5008))
    try:
        from IPython import get_ipython
        if "google.colab" in str(get_ipython()):
            print("[INFO] Detected Colab environment; setting up dependencies...")
            import subprocess
            subprocess.run(["pip", "install", "flask", "pyngrok"], check=True)
            use_ngrok = True
    except Exception:
        pass  # Not running in Colab

    if use_ngrok:
        auth_token = os.getenv("NGROK_AUTH_TOKEN")
        if not auth_token:
            raise ValueError(
                "NGROK_AUTH_TOKEN not set. Get one from https://dashboard.ngrok.com/get-started/your-authtoken"
            )

        ngrok.set_auth_token(auth_token)
        print(f"[INFO] Ngrok auth token set: {auth_token[:5]}... (masked)")

        try:
            public_url = ngrok.connect(addr=str(port), proto="http")
            print(f"[INFO] Public URL for testing in Postman: {public_url}")
        except Exception as e:
            print(f"[WARNING] Port {port} failed: {e}, retrying on port {port + 1}")
            port += 1
            public_url = ngrok.connect(addr=str(port), proto="http")
            print(f"[INFO] Public URL for testing in Postman: {public_url}")
        flask_thread = threading.Thread(target=run_flask, args=(port,), daemon=True)
        flask_thread.start()
        flask_thread.join()
    else:
        print(f"[INFO] Running Flask on port {port} without ngrok (production mode)")
        run_flask(port)

if __name__ == "__main__":
    try:
        from IPython import get_ipython  # For Colab detection
    except ImportError:
        get_ipython = lambda: None  # Fallback for non-Colab environments
    main()
